# To build and deploy to Cloud Run, run from this directory:
# $ gcloud builds submit app --config=cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats:${COMMIT_SHA}', '-f', 'Dockerfile']
    dir: 'app'
  # Run unit tests
  - name: us-central1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats
    entrypoint: python
    args: ["unit_tests.py"]
    dir: 'app'
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats:${COMMIT_SHA}']
  # Create release in Google Cloud Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: 
      [
        "beta", "deploy", "releases", "create", "rel-${SHORT_SHA}",
        "--delivery-pipeline","pop-stats-pipeline",
        "--region", "us-central1",
        "--source=", ".",
        "--annotations", "commitId=${REVISION_ID}",
        "--images", "image1=us-central1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats:${COMMIT_SHA}"
      ]
    #  - '-c'
    #  - >
    #    gcloud beta deploy releases create rel-${SHORT_SHA}
    #    --delivery-pipeline=pop-stats-pipeline --region=us-central1
    #    --source=. --annotations="commitId=${REVISION_ID}" 
    #    --images=image1=us-central1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats:${COMMIT_SHA} 
    
