apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: pop-stats
build:
  local: 
    push: false
  artifacts:
  - image: pop-stats
    context: app
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths: 
      - k8s/overlays/dev
portForward:
- resourceType: deployment
  resourceName: pop-stats
  port: 8080 
  localPort: 8080
profiles:
  - name: staging
    deploy:
      kustomize:
        paths: 
          - k8s/overlays/staging
  - name: prod
    deploy:
      kustomize:
        paths: 
          - k8s/overlays/prod
